#!/bin/bash -l
#Make our script a little bit safer
set -eo pipefail

exec gosu $POSTGRES_USER /usr/lib/postgresql/10/bin/postgres -D $POSTGRES_DATA \
-c 'config_file=/etc/postgresql/10/main/postgresql.conf'
